Daily/daily4/daily4-2/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/', views.detail, name='detail')

]

Daily/daily4/daily4-2/articles/views.py
from django.shortcuts import render,redirect
from .models import Article

# Create your views here.

def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles,
    }
    return render(request, 'articles/index.html',context)

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Article(title=title, content=content)
    article.save()
    return redirect('articles:index',article.pk)

def new(request):
    return render(request, 'articles/new.html')

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html',context)

def delete(request,pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')

Daily/daily4/daily4-2/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>DETAIL</h1>
    <h1>{{article.pk}} 번째 글</h1>
    <hr>
    <p>제목 : {{article.title}}</p>
    <p>내용 : {{article.content}}</p>
    <p>작성 시각 : {{article.created_at}}</p>
    <p>수정 시각 : {{article.updated_at}}</p>
    <hr>
    <a href="{% url 'articles:index' %}">[back]</a>
{% endblock content %}

Daily/daily4/daily4-2/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>articles</h1>
    <a href="{% url 'articles:new' %}">new</a>
    <hr>

    {% for article in articles %}
        <p>글 번호: {{article.pk}}</p>
        <p>글 제목: {{article.title}}</p>
        <p>글 내용: {{article.content}}</p>
        <br>
        <a href="{% url 'articles:detail' article.pk %}">[detail]</a>
        <form action="{% url 'articles:delete' article.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="DELETE">
        </form>
        <hr>
    {% endfor %}

{% endblock content %}

Daily/daily4/daily4-2/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}

    <h1>NEW</h1>
    <form action="{% url 'articles:create' %}" method="POST">
        {% csrf_token %}
        <label for="title">Title: </label>
        <input type="text" name="title"><br>

        <label for="content">Content: </label>
        <textarea name="content"></textarea>

        <input type="submit">
        <hr>
        <a href="{% url 'articles:index' %}">[back]</a>
    </form>

{% endblock content %}