0316_Model/Model/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
]

0316_Model/articles/urls.py
from django.urls import path 
from articles import views

app_name = 'articles'

urlpatterns = [
    path('index/',views.index, name='index'),
    path('throw/',views.throw, name='throw'),
    path('catch/',views.catch, name='catch'),
]

0316_Model/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()

0316_Model/articles/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,'articles/index.html')

def throw(request):
    return render(request,'articles/throw.html')

def catch(request):
    message = request.GET.get('message')

    context = {
        'message' : message
    }
    return render(request,'articles/catch.html',context)

0316_Model/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}

    <h1>Catch</h1>
    <h2>보낸 데이터 : {{ message }}</h2>
    <a href="{% url 'articles:throw' %}">다시 데이터 보내러 가기</a>
    
{% endblock content %}

0316_Model/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}

    <h1>여기는 index 입니다.</h1>
    
{% endblock content %}

0316_Model/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}

    <h1>Throw</h1>
    
    <form action="{% url 'articles:catch' %}">
        <label for="message">보내고 싶은 데이터 적기</label>
        <input type="text" name="message" id="message">
        <input type="submit">
    </form>
    
{% endblock content %}