0321_class/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('index/', views.index, name='index'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    # path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/', views.detail, name='detail')
]

0321_class/class_0321/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

0321_class/articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=15)
    content = models.TextField()
    image = models.ImageField(blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return f'{self.id}번째 글 - {self.title}'

0321_class/articles/forms.py
from django import forms 
from .models import Article

# class ArticleForm(forms.Form):
#     title = forms.CharField(max_length=30)
#     content = forms.CharField(widget=forms.Textarea)

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = '__all__'

    # def clean_title(self):
    #     pass

0321_class/articles/views.py
from django.shortcuts import render,redirect,get_object_or_404,get_list_or_404
from .models import Article
from .forms import ArticleForm
# Create your views here.

def index(request):
    articles = Article.objects.all()
    context = {
        'articles':articles,
    }
    return render(request, 'articles/index.html',context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save() 
        # title =	request.POST.get('title')	
        # content = request.POST.get('content')
        # article = Article(title=title,	content=content)
        # article.save()
            return redirect('articles:detail',article.pk)
        # return redirect('articles:create')
    
    else: # (or elif request.method == 'GET':)
        form = ArticleForm()
    context = {
        'form' : form
    }
    return render(request, 'articles/create.html',context)

# def new(request):
#     return render(request, 'articles/new.html')

def update(request,pk):
    # article = Article.objects.get(pk=pk)
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', pk=article.pk)
        # article.title = request.POST.get('title')
        # article.content = request.POST.get('content')
        # article.save()
        # return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'articles/update.html',context)

# def edit(request, pk):
#     article = Article.objects.get(pk=pk)
#     context = {
#         'article':article,
#     }
#     return render(request, 'articles/edit.html',context)

def detail(request,pk):
    # article = Article.objects.get(pk=pk)
    article = get_object_or_404(Article, pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html',context)

def delete(request,pk):
    # article = Article.objects.get(pk=pk)
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        redirect('articles:detail', article.pk)

0321_class/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}

    <h1>new</h1>
    <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% comment %} <label for="title">Title: </label>
        <input type="text" name="title"><br>

        <label for="content">Content: </label>
        <textarea name="content"></textarea><br> {% endcomment %}

        {{form.as_p}}

        <input type="submit">
    </form>
    <hr>
    <a href="{% url 'articles:index' %}">[back]</a>
{% endblock content %}

0321_class/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
    {% if article.image %}
        <img src="{{article.image.url}}" alt="{{article.image}}" height="300">
    {% endif %}
    <h2>DETAIL</h2>
    <h3>{{article.pk}}번 째 글</h3>
    <hr>
    <p>제목 : {{article.title}}</p>
    <p>내용 : {{article.content}}</p>
    <p>작성 시각 : {{article.created_at}}</p>
    <p>수정 시각 : {{article.updated_at}}</p>
    <hr>
    <a href="{% url 'articles:update' article.pk %}">EDIT</a>
    <br>
    <form action="{% url 'aricles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="DELETE">
    </form>
    <a href="{% url 'articles:index' %}">[back]</a>
{% endblock content %}

0321_class/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <img src="{% static 'articles/bamtol.jpg' %}" alt="bamtol" height = "300">
    <h1>Articles</h1>
    <a href="{% url 'articles:create' %}">new</a>
    <hr>
    {% for article in articles %}
        <p>글 번호 : {{article.pk}}</p>
        <a href="{% url 'articles:detail' article.pk %}">
            <p>글 제목 : {{article.title}}</p>
        </a>
        <p>글 내용 : {{article.content}}</p>
    <hr>
    {% endfor %}
{% endblock content %}

0321_class/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}

    <h1>EDIT</h1>
    <form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <!-- <label for="title">Title: </label>
        <input type="text" name="title" value="{{article.title}}">
        <br>
        <label for="content">Content: </label>
        <textarea name="content">{{article.content}}</textarea><br> -->
        <input type="submit">
    </form>
    <hr>
    <a href="{% url 'articles:detail' article.pk %}">[back]</a>
{% endblock content %}